### ISSUE TITLE
starship configuration

### ISSUE THREAD

**Issue by lucasfcm9** [diego3g/faladev#3]
compartilha suas configurações do starship (starship.toml) também. Mas no caso, só as que você julgar necessárias.

**Comment by diego3g** [comment]
Minha configuração do Starship não tem literalmente nada tirando que desabilitei 3 plugins de cloud:
```toml
"$schema" = 'https://starship.rs/config-schema.json'

[aws]
disabled=true

[azure]
disabled=true

[gcloud]
disabled=true
```

Não sei até que ponto vale compartilhar isso hehe
